apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/volumes/mongodb"
  storageClassName: manual
